name: Deploy Node.js Azure Function

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd functions/ticketmaster-ingest
          npm install

      - name: Deploy Function
        uses: azure/functions-action@v1
        with:
          app-name: event-ingest-${{ secrets.UNIQUE_SUFFIX }}
          package: ./functions/ticketmaster-ingest
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Configure Function App Settings
        run: |
            az functionapp config appsettings set \
              --name event-ingest-${{ secrets.UNIQUE_SUFFIX }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --settings TICKETMASTER_API_KEY=${{ secrets.TICKETMASTER_API_KEY }} \
                         DATALAKE_ACCOUNT_NAME=${{ secrets.DATALAKE_ACCOUNT_NAME }}
