name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set SP secret for Terraform
        run: echo "TF_VAR_sp_client_secret=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret)" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="environment=dev"
        working-directory: terraform
        env:
          TF_VAR_ticketmaster_api_key: ${{ secrets.TICKETMASTER_API_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=dev"
        working-directory: terraform
        env:
          TF_VAR_ticketmaster_api_key: ${{ secrets.TICKETMASTER_API_KEY }}


